// All site content lives here. Edit this file to add or change entries.
// category: experience | project | research | datasci | award
// status:   Shipped | In progress | Prototype | Concept | Submitted | Private code | Completed | Ongoing
// evidence kind: code | pr | live | doc | note
// cover: animated card art from js/covers.js. shots: ["assets/shots/x.png"] replaces it with real screenshots.
const GH = "https://github.com/anishtalla27";

const PROFILE = {
  name: "Anish Talla",
  tagline: "High school engineering student exploring intelligent machines and computer engineering.",
  intro:
    "I'm Anish, a student interested in software, robotics, and music. I work on tools for business operations, guitar learning, and my own daily workflow, and I study how computer-vision systems make grasping decisions. Outside those projects, I play classical and jazz guitar and teach programming and data science.",
  school: "Lightridge High School and the Academy of Engineering & Technology (Academies of Loudoun), Class of 2027",
  github: GH,
  email: "anishtalla083@gmail.com",
  resume: "assets/resume.pdf",
};

const CATEGORIES = {
  experience: "Experience",
  project: "Projects",
  research: "Research & Engineering",
  datasci: "Data Science & Open Source",
  award: "Awards & Activities",
};

const ENTRIES = [
  // ---------------------------------------------------------------- EXPERIENCE
  {
    id: "trackmyshuttle",
    cover: "pipeline",
    title: "TrackMyShuttle",
    category: "experience",
    org: "TrackMyShuttle",
    role: "Software Engineering Intern (paid)",
    dates: "Grades 11 to 12",
    status: "Private code",
    featured: true,
    privateCode: true,
    demo: "sync",
    summary:
      "Built internal and partner-facing software for a shuttle-tracking company: a multi-app workspace, partner portal, marketing tools, and the automations that keep operational data in sync.",
    problem:
      "Company operations were spread across Airtable bases, email, HubSpot, and manual steps. Teams needed usable applications on top of that data without breaking the workflows that already worked.",
    contribution:
      "I made the architectural decisions and directed development, with substantial AI collaboration on implementation. I was responsible for how the system should behave, for testing it in real authenticated sessions, and for release checks. Collaborators included a fellow developer on the events calendar and stakeholders across operations, support, and marketing.",
    tech: ["TypeScript", "React", "Vite", "Tailwind", "Node.js", "Express", "PostgreSQL", "Airtable", "Clerk", "Make", "FedEx API", "HubSpot", "Gmail API", "Replit", "AWS ECS"],
    details: [
      "TMS Hub is a TypeScript/React monorepo: separate frontends (launcher, Admin Hub, Partner Hub, Marketing Hub) over one shared backend, with shared type contracts between packages.",
      "A transactional outbox coordinates PostgreSQL writes with Airtable delivery, with idempotency protection and handling for superseded updates. The animation on this page shows the idea.",
      "Incremental sync uses a cursor rewind so records changed near pagination and timing boundaries are not missed, and schema-drift checks use stable Airtable field IDs.",
      "Authorization lives on the backend. Individual overrides can narrow a person's access but cannot accidentally expand it.",
      "Reporting distinguishes missing data from a measured zero, and single-flight caching avoids duplicate concurrent loads.",
    ],
    deliverables: [
      { name: "TMS Hub", text: "Internal workspace and access router with nine customer-lifecycle lanes, from Lead Farming through Fulfillment, Billing, Onboarding, Active, and Closure." },
      { name: "Partner Hub", text: "Partner-facing portal: account information, service lifecycle views, resources, account-team info, and maps, synchronized with Airtable." },
      { name: "Marketing Hub and event calendar", text: "Events overview, event workspaces, social calendar, email schedule, task templates, tickets, and reports. The goal was to keep the Airtable behavior and improve the interface." },
      { name: "GPOS prototype", text: "Global Partner Operating System: a configurable multi-tenant prototype with partner registry, opportunities, proposals, permissions, and auditability." },
      { name: "AI email agent", text: "Classifies incoming Gmail by category, urgency, and response need, preserves message and thread IDs, updates Airtable email logs, and links customer records." },
      { name: "Gmail follow-up tracker", text: "Monitors labeled conversations for follow-up deadlines on Eastern-time business days, with separate account sessions and queues and PostgreSQL persistence." },
      { name: "Growth demo and ROI system", text: "Plain HTML/CSS/JS pages with an Express API that route submissions into leads, ROI assessments, dashboards, and Make scenarios. Presented as a full stakeholder demo." },
      { name: "Fulfillment tooling", text: "FedEx label and tracking integration, a fulfillment quality tracker, a DYMO label-printing workflow, and inventory replacement tracking." },
      { name: "Automation and data plumbing", text: "Make blueprints for HubSpot-to-Airtable attachment sync, contract and billing-date automation, a QBR dashboard, and a geocode cache that cuts repeated location lookups." },
      { name: "Hardware", text: "Assembled and soldered GPS kits alongside the operations team." },
    ],
    outcomes: [
      "Partner platform in use by 60+ corporate partners.",
      "Internal tools used across operations, support, and marketing teams.",
    ],
    evidence: [
      { label: "Source code is private (employer-owned). See the architecture notes and animation on this page.", kind: "note" },
    ],
  },
  {
    id: "kane-ppbds",
    cover: "teach",
    title: "Data Science with Dr. David Kane",
    category: "experience",
    alsoIn: ["datasci"],
    org: "PPBDS",
    role: "Head Teaching Fellow and Data Science Intern",
    dates: "2025 to present",
    status: "Ongoing",
    featured: true,
    summary:
      "Worked with Dr. David Kane on data science education and open-source tutorial tooling. Served as a Head Teaching Fellow and contributed merged changes to the R package tutorial.helpers.",
    problem:
      "Students learn data science by running code on real data, not by memorizing definitions. The course needed tutorials, tooling, and a teaching team that made that possible at scale.",
    contribution:
      "My work had three parts: software development on shared R packages, curriculum built around interactive tutorials and real datasets, and leading the teaching team. tutorial.helpers is a shared package with several contributors. My contributions are the linked pull requests.",
    tech: ["R", "testthat", "learnr tutorials", "Quarto", "tidymodels", "Git/GitHub", "Positron", "Discord"],
    details: [
      "Software: wrote test cases for write_answers(), the function that collects student answers, and reworked the package's editor extension tooling. Both pull requests were merged by Dr. Kane in August 2025.",
      "Curriculum: reworked lessons around interactive R tutorials and roughly 15 real datasets, moving from definitions toward students running code, investigating, and forming conclusions.",
      "Leadership: progressed from Teaching Fellow to Head Teaching Fellow. Assigned fellows, ran homework workflows and quality control, managed the course Discord, held study halls, and reviewed code changes.",
      "Acknowledged in the online textbook, the Preceptor's Primer for Bayesian Data Science.",
    ],
    outcomes: [
      "150+ students across three countries.",
      "Coordinated a team of 6 to 8 teaching fellows.",
    ],
    evidence: [
      { label: "Listed under Head Teaching Fellows (bootcamp staff page source)", url: "https://github.com/PPBDS/bootcamp/blob/master/staff.qmd", kind: "doc" },
      { label: "Merged PR #75: write_answers() test cases", url: "https://github.com/PPBDS/tutorial.helpers/pull/75", kind: "pr" },
      { label: "Merged PR #81: extension changes", url: "https://github.com/PPBDS/tutorial.helpers/pull/81", kind: "pr" },
      { label: "All my tutorial.helpers pull requests", url: "https://github.com/PPBDS/tutorial.helpers/pulls?q=is%3Apr+author%3Aanishtalla27", kind: "pr" },
      { label: "tutorial.helpers package", url: "https://github.com/PPBDS/tutorial.helpers", kind: "code" },
    ],
  },
  {
    id: "littleceos",
    cover: "printer",
    title: "LittleCEOs",
    category: "experience",
    org: "LittleCEOs (nonprofit, Loudoun County)",
    role: "Software Development and Operations Intern, Project Developer Lead",
    dates: "Approx. July to November 2025",
    status: "Completed",
    summary:
      "Built the LaunchPad platform for young entrepreneurs and mentored students in CAD, 3D printing, and web development.",
    contribution:
      "Led development of LaunchPad, supported workshops, and mentored students one on one. The rule I held to: teach them to build it, do not build it for them.",
    tech: ["React", "TypeScript", "CAD", "3D printing"],
    details: [
      "Mentored students in CAD, 3D printing, filament selection, and web development.",
      "Working with kids who run real lemonade-stand-scale businesses shaped LaunchPad's Pricing Lab and feedback tools.",
    ],
    outcomes: ["10+ students mentored individually.", "Platform audience of 40+ young entrepreneurs."],
    evidence: [{ label: "LaunchPad project page", url: "project.html?id=launchpad", kind: "doc" }],
  },
  {
    id: "coderschool",
    cover: "code",
    title: "TheCoderSchool",
    category: "experience",
    org: "TheCoderSchool Ashburn",
    role: "CodeCoach (paid)",
    dates: "May 2025 to present",
    status: "Ongoing",
    summary: "Teach programming to K-8 students in small classes of 2 to 6.",
    contribution: "Plan and teach weekly sessions, adjusting projects to each student's level.",
    tech: ["Python", "Java", "JavaScript", "HTML", "Scratch"],
    details: ["Small-group format means every student ships their own project instead of copying one from the board."],
    evidence: [],
  },

  // ---------------------------------------------------------------- PROJECTS
  {
    id: "stringmap",
    cover: "fretboard",
    title: "StringMap",
    category: "project",
    role: "Creator",
    dates: "2026",
    status: "Shipped",
    featured: true,
    demo: "fretboard",
    summary:
      "A native iOS guitar-learning app that connects written music, tablature, fretboard positions, and playback. Its fingering engine uses dynamic programming to pick where on the neck to play each note.",
    problem:
      "The same pitch can be played in several places on a guitar. A passage has many technically valid fingerings, but only some are comfortable. I play classical and jazz guitar, and I wanted software that reasons about this the way a player does.",
    contribution: "Solo project: design, implementation, device QA, App Store review, and launch materials.",
    tech: ["Swift", "SwiftUI", "MusicXML", "Dynamic programming", "Audio synthesis"],
    details: [
      "A structured score pipeline reads MusicXML and bundled scores, then renders notation, tablature, and a fretboard view with synthesized playback.",
      "The fingering engine generates every valid string/fret position per note and chooses a minimum-cost route through the passage. Cost includes fret movement, position shifts, string changes, stretch, and open-string preference. Complexity is O(notes × candidates²).",
      "Profiles change the weights: beginner accessibility, staying in position, or minimizing movement. Ties break deterministically, and a user can lock one position while the surrounding notes are reoptimized.",
      "A low-D passage cannot be played as written in standard tuning. The engine reports that limitation instead of silently dropping or transposing notes. Drop D makes it playable.",
      "Photo-to-tab scanning was explored and cut. It did not meet my reliability bar, so it did not ship.",
    ],
    outcomes: ["Released on the App Store, version 1.0.0 (September 2026)."],
    evidence: [{ label: "Source code", url: GH + "/StringMap", kind: "code" }],
  },
  {
    id: "launchpad",
    cover: "chart",
    title: "LaunchPad",
    category: "project",
    org: "LittleCEOs",
    role: "Lead developer",
    dates: "2025",
    status: "Shipped",
    featured: true,
    summary:
      "A web platform where young entrepreneurs (roughly ages 8 to 14) price products, track their business, and get AI coaching. Earlier name: PriceIt.",
    problem: "Kids selling at markets and fairs rarely know if they are making money. They need tools sized for them, not a spreadsheet.",
    contribution: "Led development through LittleCEOs, including frontend, mobile responsiveness, branding, and deployment.",
    tech: ["Vite", "React", "TypeScript", "Tailwind", "shadcn/ui", "React Router", "OpenRouter / Gemini", "Vercel"],
    details: [
      "Pricing Lab walks through fixed costs, variable costs, and margins for a product.",
      "Tracks sales, expenses, events, inventory, and customer reviews.",
      "AI coach gives feedback on product ideas, and a roughly 12-week simulation lets students test decisions.",
      "Explored running a local model in the browser (WebLLM) with a hosted fallback and rule-based behavior when no API is available.",
    ],
    outcomes: ["Platform audience of 40+ young entrepreneurs."],
    evidence: [
      { label: "Live site", url: "https://www.launchpad143.com/", kind: "live" },
      { label: "Source code", url: GH + "/LaunchPad", kind: "code" },
    ],
  },
  {
    id: "visionassist",
    cover: "phone",
    title: "VisionAssist",
    category: "project",
    role: "Creator",
    status: "Prototype",
    summary: "An iOS accessibility app that pairs on-device object detection with voice interaction.",
    contribution: "Built the Swift app, including the object detector and voice manager components.",
    tech: ["Swift", "CoreML", "YOLO", "Speech"],
    details: ["YOLO models converted to CoreML run detection on device, and a voice manager handles spoken interaction."],
    evidence: [{ label: "Source code (42 commits)", url: GH + "/VisionAssist", kind: "code" }],
  },
  {
    id: "outfitassist",
    cover: "phone",
    title: "OutfitAssist",
    category: "project",
    role: "Creator",
    status: "Prototype",
    summary: "A voice-driven iOS app that uses the Claude API to help blind users identify clothing colors.",
    problem: "Picking matching clothes is a daily task that depends on color, which is hard to get without sight.",
    contribution: "Built the SwiftUI app and submitted it to TSA Software Development at the Virginia state conference.",
    tech: ["Swift", "SwiftUI", "Claude API", "Speech"],
    details: ["The whole interaction is by voice: ask, point the camera, hear the answer."],
    evidence: [],
  },
  {
    id: "pricing-simulator",
    cover: "chart",
    title: "Pricing Simulator",
    category: "project",
    role: "Creator",
    status: "Completed",
    summary: "A Python business simulation for experimenting with pricing decisions, a precursor to LaunchPad's Pricing Lab ideas.",
    tech: ["Python"],
    details: ["Standalone script-based simulator for entrepreneurship teaching."],
    evidence: [{ label: "Source code", url: GH + "/pricing-simulator", kind: "code" }],
  },
  {
    id: "meeting-transcriber",
    cover: "wave",
    title: "Meeting Transcriber",
    category: "project",
    role: "Creator",
    status: "Shipped",
    summary: "A personal macOS app that records system and microphone audio and transcribes it locally with MLX Whisper.",
    problem: "I wanted permanent, searchable transcripts without sending audio to a server.",
    contribution: "Solo project, used daily.",
    tech: ["macOS", "FFmpeg", "MLX Whisper", "Markdown"],
    details: [
      "Searchable library, editable segments, notes, bookmarks, playback with timestamp seeking, and Markdown, plain-text, and SRT export.",
      "Most of the hard work was recovery: preserving usable audio after a crash, handling empty microphone tracks, saving partial transcripts, and reducing transcription repetition.",
    ],
    evidence: [],
  },
  {
    id: "clipboardtyper",
    cover: "code",
    title: "ClipboardTyper",
    category: "project",
    role: "Creator",
    status: "Shipped",
    summary: "A small macOS utility that types clipboard text into apps that block pasting, using accessibility controls.",
    tech: ["macOS", "Accessibility API"],
    details: ["Global shortcuts and a cancel key, plus the unglamorous work of making accessibility permissions install cleanly."],
    evidence: [],
  },
  {
    id: "real-world-ready",
    title: "Real World Ready",
    category: "project",
    status: "Concept",
    summary: "An insurance education and matching app concept for early Gen Z adults: calm, personal, and not salesy.",
    tech: ["Product design"],
    details: [],
    evidence: [],
  },
  {
    id: "safesip",
    title: "SafeSip",
    category: "project",
    status: "Concept",
    summary: "A sticker-based product concept developed for the Blue Ocean entrepreneurship competition, with customer discovery across about 25 participants.",
    tech: ["Customer discovery", "Unit economics"],
    details: [],
    evidence: [],
  },
  {
    id: "earlier-projects",
    title: "Earlier projects",
    category: "project",
    status: "Completed",
    summary: "TouchSense 2.0, a country-flag game, an ethical-scenario platformer, and an Arduino Smart Shelf. Early work that got me building.",
    tech: ["Swift", "JavaScript", "Arduino"],
    details: [],
    evidence: [{ label: "GitHub profile", url: GH, kind: "code" }],
  },

  // ---------------------------------------------------------------- RESEARCH
  {
    id: "grasp-benchmark",
    cover: "grasprect",
    title: "Benchmarking Grasp Prediction",
    category: "research",
    role: "Sole author",
    dates: "2026",
    status: "Submitted",
    featured: true,
    summary:
      "A solo-authored study comparing a learned model, a detector-assisted heuristic, and zero-shot vision-language prediction for robotic grasping under one evaluation protocol.",
    problem:
      "Grasp-prediction methods are usually reported under different setups, so their scores are hard to compare. I wanted one protocol, and I wanted to know how each method fails, not just which one ranks first.",
    contribution: "Designed the protocol, ran the experiments, and wrote the manuscript through three revision rounds.",
    tech: ["Python", "PyTorch", "ResNet", "Vision-language models", "Cornell Grasping Dataset", "LaTeX"],
    details: [
      "Full title: Benchmarking Rule-Based, Learned, and Zero-Shot Vision-Language Grasp Prediction Under a Unified Evaluation Protocol.",
      "Object-wise data splits prevent leakage between training and test data. Object identities were reconstructed where the dataset does not supply them.",
      "Uncertainty estimates are clustered by object, and the systems are compared by failure type as well as score.",
      "One question: does a vision-language model's plausible grasp choice in words become unreliable once it has to be expressed as pixel coordinates?",
      "Follow-up audits compared ResNet18 and ResNet34 across multiple seeds and training budgets.",
    ],
    outcomes: ["Compared three approaches on 123 test images.", "Submitted to the Next Gen Scholar Research Paper Competition."],
    evidence: [{ label: "Code", url: GH + "/Vision-Based-Grasping", kind: "code" }],
  },
  {
    id: "adaptive-gripper",
    cover: "gripper",
    title: "Adaptive Robotic Grasping",
    category: "research",
    org: "Academy of Engineering & Technology",
    role: "Researcher",
    dates: "2026 to 2027",
    status: "In progress",
    featured: false,
    demo: "gripper",
    summary:
      "AET engineering research: a low-cost gripper that uses vision to set its initial grip, force and vibration sensing to detect slip, and real-time recovery.",
    problem:
      "Can inexpensive force and vibration feedback detect slip at or before visible motion, and start correcting within 200 milliseconds? That number is the target, not a result.",
    contribution: "Designing the apparatus, experiment, and analysis. Literature review, methods, bill of materials, and schedule planning are done.",
    tech: ["Arduino Mega", "Force-sensitive resistors", "Piezo vibration sensors", "MG996R servo", "3D printing", "OpenSCAD", "Computer vision"],
    details: [
      "Apparatus: a custom 3D-printed parallel-jaw gripper driven by one servo, with compliant fingertip pads and a fixed camera for visual ground truth.",
      "Comparison: force-only, vibration-only, and fused sensing.",
      "Planned conditions: three surface materials at 100 g, 250 g, and 400 g, plus thin plastic and foam cups for fragility tests.",
      "Metrics: precision, recall, F1, false triggers, recovery success, response time, and damage rate.",
      "Influences include Romano et al., Calandra et al., and Van Wyk and Falco.",
    ],
    evidence: [],
  },
  {
    id: "near-memory",
    cover: "chipset",
    title: "Near-Memory Computing",
    category: "research",
    org: "Academy of Engineering & Technology",
    status: "In progress",
    summary:
      "Early-stage research into the Von Neumann bottleneck: why memory bandwidth limits AI workloads and how near-memory computing addresses it.",
    tech: ["Computer architecture", "AI hardware"],
    details: ["This connects to what I want to study: AI hardware efficiency."],
    evidence: [],
  },
  {
    id: "vex",
    cover: "route",
    title: "VEX Robotics, Team 42075D",
    category: "research",
    role: "Autonomous programmer",
    status: "Ongoing",
    summary: "Program autonomous routines and motion control for a VEX V5 competition robot. State qualification reported.",
    tech: ["C++", "PROS", "LemLib", "LVGL"],
    details: ["Drivetrain and motion control, hardware integration, and a lot of iterative testing on the field."],
    evidence: [],
  },
  {
    id: "beaverworks",
    cover: "lane",
    title: "MIT Beaver Works: Autonomous Cars",
    category: "research",
    dates: "Approx. March to May 2024",
    status: "Completed",
    summary: "Saturday program coursework on autonomous vehicles using the RACECAR platform, about 5 to 6 hours per week.",
    tech: ["Python", "Computer vision", "Motion planning", "Control"],
    details: ["Topics: navigation, control, computer vision, motion planning, and probabilistic reasoning."],
    evidence: [],
  },
  {
    id: "weather-balloon",
    cover: "balloon",
    title: "Weather Balloon Mission",
    category: "research",
    role: "Mission lead",
    status: "Completed",
    summary: "Led a roughly 50-student high-altitude balloon mission coordinating 10+ Arduino sensor systems with GPS and CO₂ tracking.",
    tech: ["Arduino", "GPS", "Sensors"],
    details: [],
    evidence: [],
  },

  // ---------------------------------------------------------------- DATA SCIENCE
  {
    id: "wharton",
    cover: "sigmoid",
    title: "Wharton HS Data Science Competition",
    category: "datasci",
    dates: "2026",
    status: "Completed",
    featured: true,
    summary: "A reproducible Python pipeline predicting ice-hockey outcomes: team rankings, playoff matchup probabilities, and line disparity.",
    problem: "Predict game outcomes from season data, and show the predictions are calibrated and robust rather than lucky.",
    contribution: "Team project. I worked on the modeling pipeline and its reproducibility checks.",
    tech: ["Python", "Logistic regression", "Calibration", "Jupyter"],
    details: [
      "Win probabilities from logistic regression feed rankings and matchup predictions.",
      "Includes calibration, robustness, and reproducibility checks so every output can be regenerated.",
    ],
    evidence: [{ label: "Source code", url: GH + "/WhartonDataScience", kind: "code" }],
  },
  {
    id: "tutorial-forks",
    cover: "code",
    title: "Tutorial and curriculum repositories",
    category: "datasci",
    status: "Ongoing",
    summary: "Working forks of the PPBDS teaching packages used for my curriculum contributions. These are forks of shared projects, not original repositories.",
    tech: ["R", "learnr", "Quarto"],
    details: [],
    evidence: [
      { label: "primer.tutorials (fork)", url: GH + "/primer.tutorials", kind: "code" },
      { label: "r4ds.tutorials (fork)", url: GH + "/r4ds.tutorials", kind: "code" },
      { label: "vscode.tutorials (fork)", url: GH + "/vscode.tutorials", kind: "code" },
      { label: "ATbootcamp (fork)", url: GH + "/ATbootcamp", kind: "code" },
    ],
  },
  {
    id: "fantasy-football",
    cover: "sigmoid",
    title: "Fantasy Football Optimizer",
    category: "datasci",
    status: "Private code",
    privateCode: true,
    summary: "R scripts that optimize fantasy drafts from projected points. Built because I have followed the Seahawks since 2018.",
    tech: ["R"],
    details: [],
    evidence: [{ label: "Repository is private", kind: "note" }],
  },
  {
    id: "m3",
    title: "M3 Challenge",
    category: "datasci",
    status: "Completed",
    summary: "Team math-modeling paper on online-gambling harm, built around a Gambling Burden Ratio framework and written in LaTeX.",
    tech: ["Mathematical modeling", "LaTeX"],
    details: [],
    evidence: [],
  },
  {
    id: "tsa-geospatial",
    title: "TSA Geospatial Technology",
    category: "datasci",
    status: "Completed",
    summary: "A portfolio analyzing the urban heat island effect in Fairfax County using publicly available NASA DEVELOP data.",
    tech: ["GIS", "Remote sensing data"],
    details: [],
    evidence: [],
  },

  // ---------------------------------------------------------------- AWARDS
  {
    id: "case-competition",
    cover: "medal",
    title: "Global Case Competition: 1st place worldwide",
    category: "award",
    role: "Team PowerPoint Rangers (North America)",
    status: "Completed",
    featured: false,
    summary: "First place globally among 1,300+ teams with a Boeing strategy presentation: 10 minutes presenting, 5 minutes of Q&A.",
    details: [
      "Our recommendations were three initiatives named ClearSky, BlueWing, and SkyFocus.",
      "The prize included a $1,500 grand prize and work experience with EY.",
    ],
    tech: ["Strategy", "Financial analysis", "Presenting"],
    evidence: [],
  },
  {
    id: "ey",
    title: "EY Work Experience",
    category: "award",
    status: "Completed",
    summary: "Consulting and professional-development work, including an autonomous-driving strategy exercise for Rivian presented to EY partners.",
    tech: ["Consulting", "NPV analysis"],
    details: [],
    evidence: [],
  },
  {
    id: "cyber-cup",
    title: "Virginia Commonwealth Cyber Cup",
    category: "award",
    status: "Completed",
    summary: "First in the 9th/10th-grade division and fourth overall in Virginia.",
    tech: ["Cybersecurity"],
    details: [],
    evidence: [],
  },
  {
    id: "fbla",
    title: "FBLA",
    category: "award",
    status: "Completed",
    summary: "Second place at the state level. National qualifier and attendee.",
    tech: [],
    details: [],
    evidence: [],
  },
  {
    id: "tsa-software",
    title: "TSA Software Development",
    category: "award",
    status: "Completed",
    summary: "Fourth place at the Virginia state conference.",
    tech: ["Swift"],
    details: [],
    evidence: [],
  },
  {
    id: "pavan",
    title: "PAVAN Governor's School for the Arts",
    category: "award",
    status: "Completed",
    summary: "Selected by guitar audition in ninth grade.",
    tech: ["Classical guitar"],
    details: [],
    evidence: [],
  },
  {
    id: "usaco",
    title: "USACO",
    category: "award",
    status: "Ongoing",
    summary: "Competitive programming practice and contests.",
    tech: ["C++", "Algorithms"],
    details: [],
    evidence: [],
  },
];

const SKILLS = [
  { area: "Languages", items: ["Python", "R", "Java", "JavaScript", "TypeScript", "Swift", "C++", "Arduino C++", "SQL", "HTML/CSS"] },
  { area: "Frontend and mobile", items: ["React", "Vite", "Tailwind", "shadcn/ui", "SwiftUI"] },
  { area: "Backend and data", items: ["Node.js", "Express", "PostgreSQL", "Supabase", "Airtable"] },
  { area: "APIs and operations", items: ["Gmail", "OAuth", "FedEx", "HubSpot", "Make", "Clerk", "Mapbox", "Webhooks"] },
  { area: "AI and computer vision", items: ["Claude API", "OpenRouter / Gemini", "CoreML", "YOLO", "ResNet", "MLX Whisper"] },
  { area: "Data science", items: ["tidymodels", "Regression", "Cross-validation", "Bayesian modeling", "Causal inference", "Automated tests"] },
  { area: "Robotics and hardware", items: ["PROS V5", "LemLib", "Arduino Mega", "FSRs", "Piezo sensors", "Servos", "CAD", "3D printing"] },
  { area: "Tools", items: ["Git/GitHub", "VS Code", "Positron", "Replit", "Vercel", "OpenSCAD", "FFmpeg", "LaTeX"] },
];
